language: java
dist: trusty
sudo: required
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco-ut/jacoco.xml
jdk:
  - oraclejdk8
branches:
  only:
    - master
install:
  - cd desapp-groupj-backend
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
deploy:
  provider: heroku
  api_key:
    secure: eUl6xrcDnyXMPAwx5fdPtlMeDchFHGkV1Yb5dj95gBqvTB69HctJLyV6Y/GVhknwnI1A3MtaD20e9if/BdW930583CU8IIIadzgBO9fa22RAzpowHmW9yN0mEYYxyLl+T7mrKBvgwue0vxrL0FV1aXhLIulIGOXfSeyPwbUuh/0Udq6lQ08f7kTRKqc2zuPe/PEkQ+ru/OYo2ynrm58FMoNVpA8yZFoEhA52nV+DKrTgOfkkVYfAIhNb5N6ttY+SjJqmOPtA87yus/B4QrAPpP++RASa+6k+1Mo8ibUDQOoK+AFaYYQitheUPHdcXbq6nzOn5NClMZ9SAawasxmh8xJXRPBHQ4ypD2nQy73jZSduXe5slgQjVfUOTX8OiywG8AAk4tv6WMqq1F7NnkZPW5s47ib9GuEaGcFEykshd0nLvYGvDdYdn9p/adS+gmrg9vDqhHxZwsycbYwxgokOKNnrosXYBxJhlxJz5K7pkXxy6++vX6G3htMtUJbSaubo0zKFR8Xu6SIoI7P/pCeRH6G0DbBJLpbbuW/+LQ53FHhG4FyZnXpNE6GxTdJSmRPpsTRT0pOW11KQme9aH7LGpqCv0VOAsXvK6S1ZYEIIGzePSY2dU+gawdmup/IOAZaPhBYjRu1G/IZluWj5C8evo2VLYo3Sbb/vARzZFIZi09Y=
  app: viendas-ya-c1j
