language: java

dist: trusty

sudo: required

jdk:
  - oraclejdk8

# safelist
branches:
  only:
    - master
  
install:
  - cd desapp-groupj-backend
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8

deploy:
  provider: heroku
  api_key:
     secure: GoGo+lZ1rcknx/6MWHEROYduMZc0txWDSHM5zOQud84UXYBXDv8IhGXwxZk55o1+paeSLtuxL6eRwIN2zjSDQULntQiYGsvenAei5+9h/I4vVpkL9CE4NEINnrJNsl4kzwedOVnKxPZfMF286/6bp309JqSJSbnPcrPoGFYc7/kXaBhT94u9MMWGs87d8gW1CrGwHVRrkqH/AzizTZcYOXK5R93sLUKiTpT8UT0D1yLBMX2EY6v4xrZrheyD30awuiUerNEYv7rZ/qt+tNvT2stHGoW3t7g+ke3osuKVWF/Dn06S0UeQlYxtXnb5XItiwXe7NhN1ruVFfurEJpY+Y/oUexAQ6PKRSJOfVf3RDmAGt135waxPpQJYFZF3u6L2TpoFS9zMJcssLRfdGDKL8TqpiEmJxvt0vVGiLOeJDy+lC3fC2Tps5OpFFsiUUcwSIPnppkz+mETYtYyAkj6siqQyAN3FhH5qGVhGYZH5qBIUZ2+J4eTg/kbEUV6FJSziG1eUbRHu07J+belUGh1yoJAthCfXn2SUgO4DrdN+ccqzhUU5DXd4I6tsdEEb3MJL4XoSLhmff3tkacm+hFEqozBrtORTBEuAryG1T8ZbHVXy9LrRCKaQ/dsFY2q6zcRIcXQbRp/X6k4lL7lFKFrwx+Xk/YHVJTFNOEckAiMjp4E=
  app: viendas-ya-c1j
